services:
  # Servidor WildFly com WAR mínimo (Hello REST)
  wildfly:
    build:
      context: .
      dockerfile: Dockerfile.wildfly
    ports:
      - "8080:8080"   # HTTP
      - "9990:9990"   # Management